logging:
  config: classpath:spring-logback-dev.xml
  # path默认为当前目录的logs子目录
  # name默认为log，name为文件名，例如：配置test-log，那么生成的日志文件的全名称为test-log.log
  #file:
  #  path: logs
  #  name: log

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: xingyun-cloud-api
          uri: lb://xingyun-cloud-api
          predicates:
            - Path=/cloud-api/**
          filters:
            - StripPrefix=1
        - id: xingyun-dynamic-api
          uri: lb://xingyun-cloud-api
          predicates:
            - Path=/dynamic/web/**,/dynamic-api/**
        - id: xingyun-oss
          uri: lb://xingyun-cloud-api
          predicates:
            - Path=/oss/**